src/core/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("login/", views.MiLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(template_name="core/logout.html"), name="logout"),
    path("register/", views.MiRegisterView.as_view(), name="register"),
    
]

src/proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("producto/", include("producto.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/core/models.py
from django.db import models


class Cliente(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)

    def __str__(self) -> str:
        return f"{self.apellido}, {self.nombre}"

src/core/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    class Meta:
        model = AuthenticationForm
        fields = ["username", "password"]


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]
        help_texts = {"username": ""}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["password1"].help_text = ""
        self.fields["password2"].help_text = ""

src/core/views.py
from django.contrib import messages
from django.contrib.auth.views import LoginView
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from .forms import LoginForm, RegisterForm
from producto.models import Producto




def index(request):
    query = request.GET.get('q')  
    if query:
        productos = Producto.objects.filter(nombre__icontains=query)
    else:
        productos = Producto.objects.all()
    return render(request, 'core/index.html', {
        'productos': productos,
        'query': query,  # esto es útil si querés mostrar el término buscado
    })

def about(request):
    return render(request, "core/about.html")


class MiLoginView(LoginView):
    template_name = "core/login.html"
    authentication_form = LoginForm
    next_page = reverse_lazy("core:index")

    def form_valid(self, form):
        usuario = form.get_user()
        messages.success(self.request, f"Inicio de sesión exitoso. ¡Bienvenido {usuario.username}!")
        return super().form_valid(form)


class MiRegisterView(CreateView):
    form_class = RegisterForm
    template_name = "core/register.html"
    success_url = reverse_lazy("core:login")

    def form_valid(self, form):
        messages.success(self.request, "Registro exitoso. Ahora puedes iniciar sesión")
        return super().form_valid(form)

src/core/templates/componentes/footer.html
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Todo escabio &copy; All Rights Reserved 2025</p>
    </div>
</footer>

src/core/templates/componentes/header.html
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Todo escabio</h1>
            <p class="lead fw-normal text-white-50 mb-0">Encuentra el alcohol al mejor precio</p>
        </div>
    </div>
</header>

src/core/templates/componentes/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand fw-bold" href="{% url 'core:index' %}">Mi Negocio</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:index' %}">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:about' %}">Acerca de mí</a>
                </li>
            </ul>

            {% if user.is_authenticated %}
            <!-- Barra de búsqueda -->
            <form class="d-flex me-3" method="get" action="{% url 'core:index' %}">
                <input class="form-control rounded-pill me-2" type="search" name="q" placeholder="Buscar productos..." aria-label="Buscar">
                <button class="btn btn-outline-success rounded-pill" type="submit">Buscar</button>
            </form>
            {% endif %}

            <div class="d-flex">
                {% if user.is_authenticated %}
                    <form method="post" action="{% url 'core:logout' %}">
                        {% csrf_token %}
                        <button class="btn btn-outline-danger" type="submit">Cerrar sesión</button>
                    </form>
                {% else %}
                    <a href="{% url 'core:login' %}" class="btn btn-outline-primary">Iniciar sesión</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>